### ISSUE TITLE
Is there any way to disable the type annotation in usage?

### ISSUE THREAD

**Issue by nn1900** [bcoe/yargs#319] opened 2015-12-22 17:05 UTC
I found that the default behavior of both help and version will add '[boolean]' to the end of the option line, shown as below. I want to hide that but couldn't find a way to do that. Is this by design? Is there any way to get rid of this? 
![image](https://cloud.githubusercontent.com/assets/3831607/11961017/ddf10b7a-a910-11e5-9aca-256d9d1b1b08.png)

**Comment by nexdrew** [comment] 2015-12-23 15:45
@nn1900 Thanks for the question! This is by design, but there is a way to remove it.

Assuming you define all other options before calling `.help('help')` and `.version('...', 'version')`, this should work:

```js
var yargs = require('yargs')
  // other options here
  .help('help')
  .version('...', 'version')

yargs.getOptions().boolean.splice(-2)

console.log(yargs.argv)
```

```
$ node issue319.js --help
Options:
  --help     Show help
  --version  Show version number
```

Note that this appears to be safe for the help and version options, since they get special treatment, but messing with `yargs.getOptions()` will affect argv parsing and, so, may have undesirable side effects.

**Comment by nn1900** [comment] 2015-12-24 02:41
@nexdrew Thanks man. I have tried the solution as you mentioned above, and it works pretty well.

**Comment by nexdrew** [comment] 2015-12-24 16:41
Closing based on previous comments. :+1:

**Closed by nexdrew** 2015-12-24 16:41 UTC

**Comment by binarymist** [comment] 2018-06-07 01:48
This doesn't seem to work.

**Comment by BigstickCarpet** [comment] 2018-09-06 13:32
Here's another workaround that works for me.  The `yargs.parse()` method takes an optional callback argument.  If you specify a callback function, then Yargs will **not** display any output.  Instead, it passes the output as a string to the callback function.  You can then modify the string to remove the types.

```javascript
  function yargsCallback(err, args, output) {
    if (output) {
      // Remove types (e.g. [string], [boolean]) from the output
      output = output.replace(/\[\w+\]/g, '');
      
      // Show the modified output
      console.log(output);
    }
  }
```
